### ISSUE TITLE
useInteractions. and useClick

### ISSUE THREAD

**Issue by Ladvace** [lxsmnsyc/solid-floating-ui#4]
do this binding support `useInteractions` and `useClick` from `@floating-ui/react` or is this a different library?

**Comment by lxsmnsyc** [comment]
Interactions API was and always have been a side goal. For now, since the original implementation is a bit complex, I'm not a bit focused on that goal yet

**Comment by Ladvace** [comment]
ok thanks for the answer

**Comment by paulm17** [comment]
> Interactions API was and always have been a side goal. For now, since the original implementation is a bit complex, I'm not a bit focused on that goal yet

Just want to follow up on this.  Have you looked at the `useInteractions` code recently and is it still a bit complex?  Thanks

**Comment by lxsmnsyc** [comment]
@paulm17 I haven't really dedicated anytime to it since it's currently on my low priority. But maybe someday, no guarantees though 😉
